### ISSUE TITLE
error loading shader at res/shaders/basic_texture.vs

### ISSUE THREAD

**Issue by peebowo** [jdah/minecraft-weekend#11]
compiling with 
'''
make run
'''

compiles the game binary, but when run, produces an error.

./game
error loading shader at res/shaders/basic_texture.vs

i dont know where to go on for this, plz help :(((

**Comment by jdah** [comment]
Make sure your working directory is the base game folder - so you should be running it with `$ ./bin/game`.

**Comment by peebowo** [comment]
> Make sure your working directory is the base game folder - so you should be running it with `$ ./bin/game`.

I tried that and it worked up until the aforementioned segmentation fault.

Running MX Linux w/ sysVinit if anyones wondering
           (basically Debian)

**Comment by jdah** [comment]
Moving discussion to #12.
