### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ferdinandlb** [jdah/minecraft-weekend#12]
I have an issue when running the executable. 

![image](https://user-images.githubusercontent.com/64125945/107697481-91714f00-6cb3-11eb-8558-c010790d7474.png)

I don't know why this is happening? (Running on Debian linux)

**Comment by erikkallen** [comment]
I have the same issue this is the gdb backtrace, the readme does say to compile the static libraries before anything else but I assume the make command does this

<pre>Thread 1 &quot;game&quot; received signal SIGSEGV, Segmentation fault.
<font color="#3465A4">0x000000000071f90c</font> in <font color="#C4A000">state</font> ()
(gdb) bt
#0  <font color="#3465A4">0x000000000071f90c</font> in <font color="#C4A000">state</font> ()
#1  <font color="#3465A4">0x00007ffff7c6c9f7</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=2) at <font color="#4E9A06">msort.c</font>:142
#2  <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=2, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#3  <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=4) at <font color="#4E9A06">msort.c</font>:53
#4  <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=4, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#5  <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=8) at <font color="#4E9A06">msort.c</font>:53
#6  <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=8, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#7  <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=16) at <font color="#4E9A06">msort.c</font>:53
#8  <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=16, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#9  <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=32) at <font color="#4E9A06">msort.c</font>:53
#10 <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=32, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#11 <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=64) at <font color="#4E9A06">msort.c</font>:53
#12 <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=64, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#13 <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=128) at <font color="#4E9A06">msort.c</font>:53
#14 <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=128, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#15 <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=256) at <font color="#4E9A06">msort.c</font>:53
#16 <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=256, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#17 <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=512) at <font color="#4E9A06">msort.c</font>:53
#18 <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=512, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#19 <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=1024) at <font color="#4E9A06">msort.c</font>:53
#20 <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=1024, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#21 <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=2048) at <font color="#4E9A06">msort.c</font>:53
#22 <font color="#3465A4">0x00007ffff7c6c805</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=2048, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:53
#23 <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">p=p@entry</font>=0x7ffffffe9420, <font color="#06989A">b=b@entry</font>=0x7ffffffe9490, <font color="#06989A">n=n@entry</font>=4096) at <font color="#4E9A06">msort.c</font>:53
#24 <font color="#3465A4">0x00007ffff7c6cee6</font> in <font color="#C4A000">msort_with_tmp</font> (<font color="#06989A">n</font>=4096, <font color="#06989A">b</font>=0x7ffffffe9490, <font color="#06989A">p</font>=0x7ffffffe9420) at <font color="#4E9A06">msort.c</font>:297
#25 <font color="#C4A000">__GI___qsort_r</font> (<font color="#06989A">b</font>=&lt;optimized out&gt;, <font color="#06989A">n</font>=&lt;optimized out&gt;, <font color="#06989A">s</font>=12, <font color="#06989A">cmp</font>=0x71f90c &lt;state+2780&gt;, <font color="#06989A">arg</font>=0x411050 &lt;_ftb_cmp&gt;) at <font color="#4E9A06">msort.c</font>:297
#26 <font color="#3465A4">0x00000000004102f0</font> in <font color="#C4A000">load_empty_chunks</font> (<font color="#06989A">self</font>=0x71f650 &lt;state+2080&gt;) at <font color="#4E9A06">src/world/world.c</font>:297
#27 <font color="#3465A4">0x00000000004100b8</font> in <font color="#C4A000">world_set_center</font> (<font color="#06989A">self</font>=0x71f650 &lt;state+2080&gt;, <font color="#06989A">center_pos</font>=...) at <font color="#4E9A06">src/world/world.c</font>:373
#28 <font color="#3465A4">0x000000000040fc74</font> in <font color="#C4A000">world_init</font> (<font color="#06989A">self</font>=0x71f650 &lt;state+2080&gt;) at <font color="#4E9A06">src/world/world.c</font>:248
#29 <font color="#3465A4">0x0000000000435516</font> in <font color="#C4A000">init</font> () at <font color="#4E9A06">src/main.c</font>:17
#30 <font color="#3465A4">0x0000000000434882</font> in <font color="#C4A000">_init</font> () at <font color="#4E9A06">src/gfx/window.c</font>:119
#31 <font color="#C4A000">window_loop</font> () at <font color="#4E9A06">src/gfx/window.c</font>:149
#32 <font color="#3465A4">0x00000000004359a7</font> in <font color="#C4A000">main</font> (<font color="#06989A">argc</font>=&lt;optimized out&gt;, <font color="#06989A">argv</font>=&lt;optimized out&gt;) at <font color="#4E9A06">src/main.c</font>:106
(gdb) 
</pre>

**Comment by jdah** [comment]
Fixed in qsort issue edfeb52a8c5269cd521049e9e47211a952a263eb. Still segfaults in Linux on camera setup.

**Comment by jdah** [comment]
Same as #11, moving all discussion here.

**Comment by jdah** [comment]
OK, after some investigation, this is an alignment issue which will have to be fixed in `ecs.h` - easy fix would be making all ECS structs aligned to the maximum required alignment of any of them.

**Comment by jdah** [comment]
Fixed with 0895b3833991c04773881b662a79d4f0118a22bf! Not the best fix in the world but it works.

Can someone confirm that this works for them on linux before I close this issue? Only tested on an Ubuntu 20.10 x86_64 VM. @erikkallen @ferdinandlb

**Comment by erikkallen** [comment]
It works like a charm, tested on ubuntu 20.04 thanks! What an amazing job!
