### ISSUE TITLE
Can you make a release please?

### ISSUE THREAD

**Issue by AAli107** [jdah/minecraft-weekend#14]
I don't know how to run your game through source code, can you make a release so that we can play straight from the exe file?

**Comment by cjtim** [comment]
I don't think it's windows supported. Only MacOS, Unix I guess.

**Comment by TheArcaneBrony** [comment]
^ there is no official Windows support.

**Comment by jdah** [comment]
No, sorry, not something I'm going to maintain esp. with further updates.
If someone wants to fork and do that it's totally OK (allowed in the license) but not something I have time for myself.

**Comment by UniqueName12345** [comment]
> No, sorry, not something I'm going to maintain esp. with further updates. If someone wants to fork and do that it's totally OK (allowed in the license) but not something I have time for myself.

As said by the person who made a release for MICROCRAFT.
