### ISSUE TITLE
Error loading shader at res/shaders/basic_texture.vs

### ISSUE THREAD

**Issue by infinitygamer404** [jdah/minecraft-weekend#16]
I compiled the source, and when i tried to execute the game binary, it says `error loading shader at res/shaders/basic_texture.vs
`

**Comment by darshkpatel** [comment]
I had the same issue,
instead of going into the 'bin' directory and doing `./game`
stay in the parent directory and do `./bin/game`

**Comment by infinitygamer404** [comment]
Ohh... Yeah that works
Thanks!
