### ISSUE TITLE
Game is not opening

### ISSUE THREAD

**Issue by OBCUNITED** [jdah/minecraft-weekend#19]
There is no way to open it.
If it was .py type i can just type 
`
app{} = run
`
and the game starts but idk how to do that in c/c++

**Comment by a-random-person-991** [comment]
you have to compile it

**Comment by jdah** [comment]
Please read README.md

**Comment by dedshit** [comment]
> There is no way to open it.
> If it was .py type i can just type
> `app{} = run`
> and the game starts but idk how to do that in c/c++


lmao 😂😂😂  just learn c
