### ISSUE TITLE
Unable to compile on Linux 

### ISSUE THREAD

**Issue by Error916** [jdah/minecraft-weekend#2]
The clang - framework flag is not available in Linux so it not possible to compile the project

**Comment by Asandax6** [comment]
> The clang - framework flag is not available in Linux so it not possible to compile the project

It won't run on Linux window.h is a windows Library for Building the Window. You can use the other parts of the code and use another window library that supports Linux. I will try and do that once I learn how to code in C++.

**Comment by jdah** [comment]
@Asandax6 that's not the case, there is no dependency on Windows. `window.h` is in fact just one of the header files.
@Error916 Linux builds *should* be fixed now with the most recent updates to the `Makefile`. `-framework` flags have been made OS-dependent :)

**Comment by Error916** [comment]
there is a problem in src/world/blockmesh.c and in src/world/light.c the #include "block.h" is broken so need to be changed to #include "../block/block.h"

**Comment by erentar** [comment]
lib/cglm and lib/glfw are empty.

**Comment by jdah** [comment]
Libraries have been added as submodules, builds work now.
