### ISSUE TITLE
error loading shader at res/shaders/basic_texture.vs

### ISSUE THREAD

**Issue by ZeusThundr** [jdah/minecraft-weekend#20]
Ran `make libs` then make in minecraft-weekend directory everything built fine.
but when I run the game binary the terminal outputs $ error loading shader at res/shaders/basic_texture.vs

I'm new to linux this is a fresh install anything I can do to fix this on my part?
OS: Pop OS 20.10
Nvidia Driver Version 460.39
GPU: RTX 2080-TI

**Comment by Andrew-Pynch** [comment]
Same here, anyone else had this issue?

**Comment by Andrew-Pynch** [comment]
@ZeusThundr this is a duplicate issue. https://github.com/jdah/minecraft-weekend/issues/16

The solution is to run the game as
```
./bin/game
```
from root directory instead of trying to run
```
./game
```
from bin directory. Weird but works.

**Comment by jdah** [comment]
@Andrew-Pynch exactly right. Running from the root dir is the solution, closing this issue.
