### ISSUE TITLE
Feature request: Crosshair, hotbar, block outline, escape window

### ISSUE THREAD

**Issue by YHDiamond** [jdah/minecraft-weekend#29]
I just came to request a few things that I would guess are not that hard to make that I would implement myself but I know absolutely zero C, only Java. 

1. A crosshair in the center of the screen so you can know what block you are facing directly, I would guess this would simply be an overlay.
2. A hotbar at the bottom of the screen so you can know what blocks are what number, also probably not too hard, no rendering 3d things...
3. This might be a bit more challenging but that black block outline around the block you are looking at should appear... It shouldn't be *too* hard if you know what block they are looking at... right?
4. An escape window themed after Minecraft but it just has a simple quit button but when you press escape your cursor will leave and you can escape the window.

**Comment by jdah** [comment]
These have already been in for months. There's a crosshair, hotbar, and outline of the current block being looked at if you build/run the most recent version.

**Comment by YHDiamond** [comment]
Oh sorry lol I looked in readme and it didn't say those were added, you might wanna say that??
