### ISSUE TITLE
Memory leak on linux

### ISSUE THREAD

**Issue by ghost** [jdah/minecraft-weekend#30]
1. Run the game
2. Look at the RAM usage in the system monitor 

It doesn't stop after the chunks are loaded, it goes upto 1Gb and more, didn't test any further.
Is it suppose to load so much?

**Comment by jdah** [comment]
Yes, it is, there isn't a leak - memory usage is stable on all machine I have tested on.  If you can really find one please `valgrind` it (or something similar) and post results.
