### ISSUE TITLE
wsl + x410 mouse control

### ISSUE THREAD

**Issue by necrogami** [jdah/minecraft-weekend#31]
For some reason when using WSL and X410 the mouse can only barely control the movement. it takes like 200+ mouse movements to turn 180 degrees

**Comment by dzhigit1** [comment]
I think I have same issue on GNU/Linux itself. Changing to my monitor's native refresh rate, 144 Hz, helps a lot. If you are on 144 Hz and switch to 60 Hz, run the game, then switch back to 144, it might make it better.

**Comment by necrogami** [comment]
I no longer use x410
