### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by dzhigit1** [jdah/minecraft-weekend#33]
I think I almost figured out build on Windows but I have this issue:

`error: TIME_UTC 'undeclared'`

src/util/time.h:11:23 is:

`timespec_get(&ts, TIME_UTC);`

I guess Windows does not implement TIME_UTC thing. I am not C programmer unfortunately. Is there workaround?

**Comment by jdah** [comment]
I don't have a windows machine to test, but it actually doesn't matter what that second parameter is. If you can find a legal value it should work fine (it's only used for difference so the locality of the time doesn't matter).

**Comment by dzhigit1** [comment]
I changed it to 1000000. Works in GNU/Linux and gets past that error in Windows. However now on Windows I think I am running in to #23 . No 2 implementations of that qsort_r or qsort_s are the same...

**Comment by jdah** [comment]
Merging with #23.

**Comment by dzhigit1** [comment]
I don't think the issue is #23 but they're related. After trying in GCC I tried in clang, and it gave the same error.
```
clang -o src/world/world.o -c src/world/world.c -std=c11 -O3 -g -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wno-pointer-arith -Wno-newline-eof -Wno-unused-parameter -Wno-gnu-statement-expression -Wno-gnu-compound-literal-initializer -Wno-gnu-zero-variadic-macro-arguments -Ilib/cglm/include -Ilib/glad/include -Ilib/glfw/include -Ilib/stb -Ilib/noise -fbracket-depth=1024
In file included from src/world/world.c:4:
src/world/../util/sort.h:33:25: error: variable has incomplete type 'struct _sort_r_data'
    struct _sort_r_data tmp = {arg, cmp};
                        ^
src/world/../util/sort.h:33:12: note: forward declaration of 'struct _sort_r_data'
    struct _sort_r_data tmp = {arg, cmp};
           ^
src/world/../util/sort.h:34:33: error: use of undeclared identifier 'sort_r_arg_swap'; did you mean '_sort_r_arg_swap'?
    qsort_s(*base, nel, width, &sort_r_arg_swap, &tmp);
                                ^~~~~~~~~~~~~~~
                                _sort_r_arg_swap
src/world/../util/sort.h:13:12: note: '_sort_r_arg_swap' declared here
static int _sort_r_arg_swap(void *s, const void *aa, const void *bb) {
           ^
src/world/world.c:235:11: warning: implicit declaration of function 'timespec_get' is invalid in C99 [-Wimplicit-function-declaration]
    SRAND(NOW());
          ^
src/world/../gfx/../util/time.h:11:5: note: expanded from macro 'NOW'
    timespec_get(&ts, 100);\
    ^
1 warning and 2 errors generated.
mingw32-make: *** [Makefile:46: src/world/world.o] Error 1
```
I don't know C but sort.h seems to be buggy. I fixed sort.h:34:33 by changing &sort_r_arg_swap to &_sort_r_arg_swap but don't know if it's the right fix, and it's failing because of sort.h:33:25. Can this issue be reopened?

#47
