### ISSUE TITLE
Can't build on a mac

### ISSUE THREAD

**Issue by valvhammer** [jdah/minecraft-weekend#35]
I tried to build it on a mac but I can't build it and makefile dosen't work

It gives me a permission denied error

Can someone help?

**Comment by jdah** [comment]
Please include the exact error you're getting.

**Comment by valvhammer** [comment]
`-bash: /Users/macbookpro/minecraft-weekend/Makefile: Permission denied`

This is the error i get

plus if i try to build it with gcc, it dosent work

**Comment by 0x14307** [comment]
try "sudo make"

**Comment by valvhammer** [comment]
i get this error if i try to use that:`
mkdir -p ./bin
cd lib/cglm && cmake . -DCGLM_STATIC=ON && make
/bin/sh: cmake: command not found
make: *** [libs] Error 127
`
i have `cmake`

**Comment by ghost** [comment]
> i have `cmake`

How did you install `cmake`? Did you perhaps installed it via [homebrew](https://brew.sh/)?

**Comment by valvhammer** [comment]
> > i have `cmake`
> 
> How did you install `cmake`? Did you perhaps installed it via [homebrew](https://brew.sh/)?

installed from cmake.org

**Comment by 0x14307** [comment]
Try installing through homebrew

**Comment by jdah** [comment]
@AnonimFan please make sure `cmake` is in your `PATH` before you run the makefile, whether you install it from homebrew or cmake.org. You'll also probably need to change the `CC` variable in the makefile to `gcc` if that's all you have installed. and, please, if you keep getting errors, say what the error you got is in the comment. It's hard to help if something just "doesn't work". 

EDIT: also you shouldn't need to `sudo make` to build this. Something is wrong on your machine either with the permissions on the makefile (try `chmod`ing it to something reasonable) or on `make` or one of its dependencies.

**Comment by Monsterray** [comment]
I tried building this project and was able to build the libs, but when I try to make the main program it gives me an error.

[Here.](https://pastebin.com/YaMp9w9D)

**Comment by jdah** [comment]
@Monsterray Please open a separate issue. Just taking a look at it here though, something is missing out of your `time.h` which is an issue with the platform you're building on.

**Comment by valvhammer** [comment]
i get this error now:`src/gfx/window.c:158:25: error: use of undeclared identifier 'TIME_UTC'` Please help;

EDIT:Libaries were fine, just a couple of warnings

EDIT2:I fixed some errors with adding "#include "util/time.h"" into window.c, then i get this error when building:`src/gfx/window.c:2:10: fatal error: 'util/time.h' file not found`

EDIT3:if i try to run `make` it gives me this error:`error: unable to open output file 'src/glad.o': 'Operation not permitted'` i can only make it with `sudo make` for some reason

**Comment by valvhammer** [comment]
If i put 1 instead of TIME_UTC in time.h i get this error:`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Please help

if i try to compile anything else with gcc same linking error

**Comment by ghost** [comment]
Whatever you are doing, I can not reproduce this.
~~But did you install xcode command line tools with `xcode-select --install?~~ What use does this offer?
Can you re-clone the repository again?
> If i put 1 instead of TIME_UTC in time.h i get this error:`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

It still works on mine.

**Comment by valvhammer** [comment]
> Can you re-clone the repository again?





maybe that will work

**Comment by valvhammer** [comment]
> If i put 1 instead of TIME_UTC in time.h i get this error:`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
> 
> Please help
> 
> if i try to compile anything else with gcc same linking error

now i know the issue, LINKING FAILS somehow
somthing that i recommend is to put the game binary to releases

**Comment by ghost** [comment]
> somthing that i recommend is to put the game binary to releases

Also: jdah/minecraft-weekend#38

**Comment by valvhammer** [comment]
![image](https://user-images.githubusercontent.com/70202298/121048042-b6378800-c7b6-11eb-87f1-f8c70ad34b1d.png)
this should work tho(will need to define something in utils/time.h)

**Comment by ghost** [comment]
> this should work tho(will need to define something in `utils/time.h`)

Well, if it does not exist, then there is probably something wrong with the libraries or something.

**Comment by valvhammer** [comment]
ookay. so i upgraded to catalina, but now, i get this error:
```
/Users/macbookpro/minecraft-weekend/lib/cglm/src/../include/cglm/common.h:21:10: fatal error: 'math.h' file not found
#include <math.h>
         ^~~~~~~~
1 error generated.
```
like gcc/clang, whats your issue????

**Comment by valvhammer** [comment]
able to build, closed
