### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by JanPoonthong** [jdah/minecraft-weekend#36]
Error: 
```
mkdir -p ./bin
cd lib/cglm && cmake . -DCGLM_STATIC=ON && make
/bin/sh: 1: cmake: not found
make: *** [Makefile:28: libs] Error 127
```

I tried to run `make` command, every time I get this error above.

**Comment by JanPoonthong** [comment]
Maybe I don't have cmake and that causes the error, but I would like you to mention that cmake is required in order to build this project.

**Comment by jdah** [comment]
This is definitely just `cmake` missing. Do you have any other errors after that?

**Comment by JanPoonthong** [comment]
Error:
```
make[3]: Leaving directory '/home/jan/Tmp/minecraft-weekend/lib/cglm'
[100%] Built target cglm
make[2]: Leaving directory '/home/jan/Tmp/minecraft-weekend/lib/cglm'
make[1]: Leaving directory '/home/jan/Tmp/minecraft-weekend/lib/cglm'
cd lib/glad && clang -o src/glad.o -Iinclude -c src/glad.c
/bin/sh: 1: clang: not found
make: *** [Makefile:29: libs] Error 127
```
Yes, I got more errors ... I need `clang` also.

**Comment by JanPoonthong** [comment]
After installing `cmake` and `clang`, the project builds. I might submit a PR on your README.md for adding requirements.

**Comment by ghost** [comment]
You could have installed `build-essential` by your package manager (like `apt`) or something.
