### ISSUE TITLE
GLFW error 65543: GLX: Failed to create context: BadValue (integer parameter out of range for operation) error creating window

### ISSUE THREAD

**Issue by Carbolemons** [jdah/minecraft-weekend#42]
I attached the stdout of make when building this game.

[minecraft-weekend.make.log](https://github.com/jdah/minecraft-weekend/files/6427768/minecraft-weekend.make.log)
[minecraft-weekend.make.warnings.log](https://github.com/jdah/minecraft-weekend/files/6427769/minecraft-weekend.make.warnings.log)
[minecraft-weekend.makelibs.log](https://github.com/jdah/minecraft-weekend/files/6427770/minecraft-weekend.makelibs.log)

upon running ./bin/game in the root of the git repository, I receive this error
`GLFW error 65543: GLX: Failed to create context: BadValue (integer parameter out of range for operation) error creating window`

---------------------- 
OS: Linux Mint 19.3 Tricia x86_64 
Kernel: 5.4.0-71-generic 
Uptime: 2 days, 1 hour, 55 mins 
Packages: 3582 
Shell: zsh 5.4.2 
Resolution: 1920x1080, 2560x1080 
DE: Cinnamon 4.4.8 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark-Minty-er (Mint-Y)
Theme: Minty [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i9-9900K (16) @ 5.000GHz 
GPU: NVIDIA GeForce GTX 1180 
Memory: 5830MiB / 32030MiB

**Comment by cheloveg** [comment]
Hey, how did you fix it?
