### ISSUE TITLE
At random runs you spawn in a never-ending hole

### ISSUE THREAD

**Issue by Ccode-lang** [jdah/minecraft-weekend#53]
![Snip20210624_1](https://user-images.githubusercontent.com/78437178/123333429-bd2cfd00-d50f-11eb-9d45-b071acb82871.png)

**Comment by nickpapoutsis** [comment]
Congrats! You found the real life simulation.

**Comment by Ccode-lang** [comment]
Wow... But really how do you fix this?

**Comment by andreanidouglas** [comment]
i'm not sure if it was a fluke, i had the same issue. compiling with clang solved it though

**Comment by Ccode-lang** [comment]
ok thanks!
