### ISSUE TITLE
The directory "/mnt/dev/mcwk/lib/cglm" doesn't contain CMakeLists.txt

### ISSUE THREAD

**Issue by manen** [jdah/minecraft-weekend#64]
Exact steps:

```
git clone https://github.com/jdah/minecraft-weekend mcwk
cd mcwk
make
```

Output of `make`:

```
mkdir -p ./bin
cd lib/cglm && cmake . -DCGLM_STATIC=ON && make
CMake Error: The source directory "/mnt/dev/minecraft-weekend/lib/cglm" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [Makefile:28: libs] Error 1
```

I'm not sure what I'm supposed to do about this

**Comment by Ccode-lang** [comment]
Why are you in a drive when executing?
And also you cloned to minecraft-weekend folder and went into mcwk.

**Comment by manen** [comment]
that's where all my code is, and i cloned into mcwk, just copied the wrong command. sorry

**Comment by jdah** [comment]
Please read the README. It says explicitly to use `--recurse-submodules` on the `git clone` command.

**Comment by manen** [comment]
oh, thanks.
