### ISSUE TITLE
src/world/light.c:2:10: fatal error: 'block.h' file not found

### ISSUE THREAD

**Issue by K4mey** [jdah/minecraft-weekend#7]
```src/world/light.c:2:10: fatal error: 'block.h' file not found
#include "block.h"
         ^~~~~~~~~
1 error generated.
make: *** [Makefile:39: src/world/light.o] Error 1
```

Arch Linux 64bit
GNU Make 4.3
cmake version 3.19.4

- just wanted to test it after watching your video, i have no intentions in forking it and continuing the project.

**Comment by jdah** [comment]
Fixed in most recent update a9f79d6.
