### ISSUE TITLE
Switch to gitlab

### ISSUE THREAD

**Issue by CrezyDud** [jdah/minecraft-weekend#70]
This would greatly reduce spam and newbs (most likely(and windows pricks))

**Comment by Ccode-lang** [comment]
It is probably a better idea to keep it here. The people trying to build on windows are only trying to add to the build instructions.  

Also, people who are "newbs" may just be people who don't know much about the c language.  

Along with that, this project is not being developed currently and was only a small project.

**Comment by TheTechRobo** [comment]
People can easily sign up for GitLab too. The only reason IMO to switch is because it's open source.

**Comment by Ccode-lang** [comment]
GitHub is open source. I don't get what you mean.

**Comment by TheTechRobo** [comment]
Huh? GitHub's website is _not_ open source.
https://stackoverflow.com/questions/24254324/is-github-com-source-code-open-source

**Comment by jdah** [comment]
Thanks for the suggestion, but I find it a little funny that you're spamming on GitHub with a non-issue about moving to another platform in order to reduce spam :-) I'm going to keep the project here for now, whatever issues I might have with GitHub.

**Comment by ghost** [comment]
ya, alright, ok, i sounded a lots angry (what was that day with me)
but did you have to close me out of issues?
