### ISSUE TITLE
Don't know if it's an "issue" but I've created a compile script and didn't know where to put it so anyone can see it.

### ISSUE THREAD

**Issue by Lampe2020** [jdah/minecraft-weekend#71]
I've created a script that automatically downloads minecraft-weekend and compiles it. It needs apt and git. I've put it on my web page as [minecraft-weekend.sh](https://dateien.lampe2020.de/dateien/minecraft-weekend/minecraft-weekend.sh) but I think it does only work on Debian and Debian-related Linux builds like [Ubuntu](https://ubuntu.com/download) and [Linux Mint](https://www.linuxmint.com/download.php).

**Comment by Lampe2020** [comment]
jdah, you can close this "issue" now but please leave it visible or (even better:) include a link to my script in the "readme.md" file.

**Comment by jdah** [comment]
Thanks, it'll still be visible in the closed issues tab - I think the necessary libs can be found from trying to run `make` on most systems though.

**Comment by Lampe2020** [comment]
👍

**Comment by TheTechRobo** [comment]
Getting a 404 when going to that page

**Comment by Lampe2020** [comment]
Sorry, I changed the path to [https://dateien.lampe2020.de/dateien/minecraft-weekend/minecraft-weekend.sh](https://dateien.lampe2020.de/dateien/minecraft-weekend/minecraft-weekend.sh) and with that I made the old path invalid...

**Comment by Lampe2020** [comment]
If the build process fails after running the script, delete the folder "minecraft-weekend" from your PC and re-run the script.   
If that doesn't help, look what the output says and then try to troubleshoot that.   
To get more time to look at the output try: `~$ ./minecraft-weekend.sh &>> mcwe-install.log` with the `~$` being your terminal's input prompt.   
When the prompt appears again you can open mcwe-install.log with any text editor you like.   
   
Note: it may take a while for the prompt to appear again!
